using System.Globalization;
using AudiobookMeta.Tool.Common;
using Tomlyn;
using Tomlyn.Model;

namespace AudiobookMeta.Tool.Configuration;

public sealed record ConfigDefaultDifference(
    string Key,
    string CurrentValue,
    string DefaultValue,
    bool GeneratedDefaultCandidate,
    string Reason);

public sealed record ConfigMigrationStatus(
    string Path,
    int? RecordedTemplateVersion,
    int CurrentTemplateVersion,
    IReadOnlyList<ConfigDefaultDifference> Differences);

public sealed record ConfigMigrationChange(string Key, string? PreviousValue, string Value);

public sealed record ConfigMigrationResult(
    string Path,
    bool DryRun,
    int? PreviousTemplateVersion,
    int TemplateVersion,
    IReadOnlyList<ConfigMigrationChange> Changes,
    IReadOnlyList<ConfigDefaultDifference> PreservedDifferences);

public sealed class ConfigMigrationService(ConfigPathResolver paths)
{
    public ConfigMigrationStatus Status(string? explicitPath)
    {
        var (path, root) = Load(explicitPath);
        var recorded = OptionalInteger(root, "template_version");
        var differences = Differences(root, recorded);
        return new(path, recorded, DefaultConfigFile.TemplateVersion, differences);
    }

    public ConfigMigrationResult Migrate(
        string? explicitPath,
        IEnumerable<string> applyKeys,
        bool applyAllGeneratedDefaults,
        bool dryRun)
    {
        var (path, root) = Load(explicitPath);
        var previousVersion = OptionalInteger(root, "template_version");
        var differences = Differences(root, previousVersion);
        var explicitKeys = applyKeys.Distinct(StringComparer.OrdinalIgnoreCase).ToList();
        var unknown = explicitKeys.Where(key => differences.All(item => !item.Key.Equals(key, StringComparison.OrdinalIgnoreCase))).ToList();
        if (unknown.Count > 0)
            throw new AudiobookMetaException(
                $"Configuration migration key is not available: {string.Join(", ", unknown)}.",
                ExitCodes.Usage,
                "Run 'dotnet audiobookmeta config status' to inspect adoptable default differences.");

        var adoptGeneratedDefaults = applyAllGeneratedDefaults || dryRun && explicitKeys.Count == 0;
        var selected = differences.Where(difference => explicitKeys.Contains(difference.Key, StringComparer.OrdinalIgnoreCase)
            || adoptGeneratedDefaults && difference.GeneratedDefaultCandidate).ToList();
        var changes = selected.Select(difference => new ConfigMigrationChange(
            difference.Key, difference.CurrentValue == "<missing>" ? null : difference.CurrentValue, difference.DefaultValue)).ToList();
        var canAdvanceTemplate = differences.Where(difference => difference.GeneratedDefaultCandidate)
            .All(difference => selected.Contains(difference));
        if (canAdvanceTemplate && previousVersion != DefaultConfigFile.TemplateVersion)
            changes.Add(new("template_version", previousVersion?.ToString(CultureInfo.InvariantCulture), DefaultConfigFile.TemplateVersion.ToString(CultureInfo.InvariantCulture)));

        if (!dryRun && changes.Count > 0)
        {
            foreach (var difference in selected)
                Apply(root, difference);
            if (canAdvanceTemplate)
                root["template_version"] = DefaultConfigFile.TemplateVersion;
            Save(path, root);
        }

        var preserved = differences.Except(selected).ToList();
        return new(path, dryRun, previousVersion, DefaultConfigFile.TemplateVersion, changes, preserved);
    }

    private static IReadOnlyList<ConfigDefaultDifference> Differences(TomlTable root, int? recordedVersion)
    {
        var differences = new List<ConfigDefaultDifference>();
        if (Find(root, "providers.libex.region") is { } regionValue)
        {
            var region = Convert.ToString(regionValue, CultureInfo.InvariantCulture) ?? string.Empty;
            if (!region.Equals("de", StringComparison.OrdinalIgnoreCase))
            {
                var generated = recordedVersion is null or < 2
                    && region.Equals("us", StringComparison.OrdinalIgnoreCase)
                    && Convert.ToString(Find(root, "providers.libex.type"), CultureInfo.InvariantCulture)
                        ?.Equals("libex", StringComparison.OrdinalIgnoreCase) is true;
                differences.Add(new(
                    "providers.libex.region",
                    region,
                    "de",
                    generated,
                    generated
                        ? "value matches the Libex marketplace generated by template version 1"
                        : "value differs from the current default and is treated as an explicit customization"));
            }
        }
        var legacyTemplate = recordedVersion is null or < 2;
        if (Find(root, "providers.audible-de") is null)
        {
            differences.Add(new(
                "providers.audible-de",
                "<missing>",
                "Audible Germany provider",
                legacyTemplate,
                legacyTemplate
                    ? "provider was added by template version 2"
                    : "current template provider is missing and is treated as an explicit customization"));
        }
        if (Find(root, "groups.audible") is not TomlArray audibleGroup)
        {
            differences.Add(new(
                "groups.audible",
                "<missing>",
                "audible-de",
                legacyTemplate,
                legacyTemplate
                    ? "provider group was added by template version 2"
                    : "current template group is missing and is treated as an explicit customization"));
        }
        else if (!audibleGroup.OfType<string>().Contains("audible-de", StringComparer.OrdinalIgnoreCase))
        {
            differences.Add(new(
                "groups.audible",
                string.Join(',', audibleGroup.OfType<string>()),
                string.Join(',', audibleGroup.OfType<string>().Append("audible-de")),
                false,
                "existing group is customized and will be preserved unless selected explicitly"));
        }
        return differences;
    }

    private (string Path, TomlTable Root) Load(string? explicitPath)
    {
        var path = paths.Resolve(explicitPath);
        if (!File.Exists(path) && paths.UsesPlatformDefault(explicitPath))
            DefaultConfigFile.Create(path);
        if (!File.Exists(path))
            throw new AudiobookMetaException(
                $"Configuration file was not found: {path}", ExitCodes.Configuration,
                "Select an existing file with BOOKMETA_CONFIG/--config.");
        try
        {
            var root = TomlSerializer.Deserialize<TomlTable>(File.ReadAllText(path), new TomlSerializerOptions { SourceName = path });
            return (path, root ?? throw ConfigError("configuration is empty"));
        }
        catch (TomlException exception)
        {
            throw new AudiobookMetaException(
                $"Configuration is invalid: {exception.Message}", ExitCodes.Configuration,
                "Correct the TOML syntax before inspecting or migrating defaults.", exception);
        }
    }

    private static void Save(string path, TomlTable root)
    {
        try
        {
            var content = TomlSerializer.Serialize(root, new TomlSerializerOptions { WriteIndented = true });
            DefaultConfigFile.WriteAtomically(path, content.EndsWith('\n') ? content : content + Environment.NewLine);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException or TomlException)
        {
            throw new AudiobookMetaException(
                $"Could not update the configuration file: {path}", ExitCodes.Configuration,
                "Check that the file is writable and valid TOML, then retry.", exception);
        }
    }

    private static int? OptionalInteger(TomlTable root, string key)
        => root.TryGetValue(key, out var value) ? Convert.ToInt32(value, CultureInfo.InvariantCulture) : null;

    private static object? Find(TomlTable root, string key)
    {
        object? current = root;
        foreach (var part in key.Split('.'))
        {
            if (current is not TomlTable table || !table.TryGetValue(part, out current))
                return null;
        }
        return current;
    }

    private static void Apply(TomlTable root, ConfigDefaultDifference difference)
    {
        if (difference.Key == "providers.audible-de")
        {
            var providers = root["providers"] as TomlTable ?? (TomlTable)(root["providers"] = new TomlTable());
            providers["audible-de"] = new TomlTable
            {
                ["type"] = "audible",
                ["base_url"] = "https://api.audible.de",
                ["enabled"] = true,
                ["region"] = "de",
                ["priority"] = 85L,
                ["groups"] = Array("audible")
            };
            return;
        }
        if (difference.Key == "groups.audible")
        {
            var groups = root["groups"] as TomlTable ?? (TomlTable)(root["groups"] = new TomlTable());
            var members = groups.TryGetValue("audible", out var configured) && configured is TomlArray existing
                ? existing
                : [];
            if (!members.OfType<string>().Contains("audible-de", StringComparer.OrdinalIgnoreCase))
                members.Add("audible-de");
            groups["audible"] = members;
            return;
        }

        var parts = difference.Key.Split('.');
        var table = root;
        foreach (var part in parts[..^1])
            table = table[part] as TomlTable ?? throw ConfigError($"missing table '{part}'");
        table[parts[^1]] = difference.DefaultValue;
    }

    private static TomlArray Array(params string[] values)
    {
        var array = new TomlArray();
        foreach (var value in values)
            array.Add(value);
        return array;
    }

    private static AudiobookMetaException ConfigError(string message)
        => new($"Configuration migration failed: {message}.", ExitCodes.Configuration,
            "Run 'dotnet audiobookmeta config validate' and correct the file before retrying.");
}
