using System.Globalization;
using AudiobookMeta.Tool.Common;
using Tomlyn;
using Tomlyn.Model;

namespace AudiobookMeta.Tool.Configuration;

public sealed record ConfigDefaultDifference(
    string Key,
    string CurrentValue,
    string DefaultValue,
    bool GeneratedDefaultCandidate,
    string Reason);

public sealed record ConfigMigrationStatus(
    string Path,
    int? RecordedTemplateVersion,
    int CurrentTemplateVersion,
    IReadOnlyList<ConfigDefaultDifference> Differences);

public sealed record ConfigMigrationChange(string Key, string? PreviousValue, string Value);

public sealed record ConfigMigrationResult(
    string Path,
    bool DryRun,
    int? PreviousTemplateVersion,
    int TemplateVersion,
    IReadOnlyList<ConfigMigrationChange> Changes,
    IReadOnlyList<ConfigDefaultDifference> PreservedDifferences);

public sealed class ConfigMigrationService(ConfigPathResolver paths)
{
    public ConfigMigrationStatus Status(string? explicitPath)
    {
        var (path, root) = Load(explicitPath);
        var recorded = OptionalInteger(root, "template_version");
        var differences = Differences(root, recorded);
        return new(path, recorded, DefaultConfigFile.TemplateVersion, differences);
    }

    public ConfigMigrationResult Migrate(
        string? explicitPath,
        IEnumerable<string> applyKeys,
        bool applyAllGeneratedDefaults,
        bool dryRun)
    {
        var (path, root) = Load(explicitPath);
        var previousVersion = OptionalInteger(root, "template_version");
        var differences = Differences(root, previousVersion);
        var explicitKeys = applyKeys.Distinct(StringComparer.OrdinalIgnoreCase).ToList();
        var unknown = explicitKeys.Where(key => differences.All(item => !item.Key.Equals(key, StringComparison.OrdinalIgnoreCase))).ToList();
        if (unknown.Count > 0)
            throw new AudiobookMetaException(
                $"Configuration migration key is not available: {string.Join(", ", unknown)}.",
                ExitCodes.Usage,
                "Run 'dotnet audiobookmeta config status' to inspect adoptable default differences.");

        var adoptGeneratedDefaults = applyAllGeneratedDefaults || dryRun && explicitKeys.Count == 0;
        var selected = differences.Where(difference => explicitKeys.Contains(difference.Key, StringComparer.OrdinalIgnoreCase)
            || adoptGeneratedDefaults && difference.GeneratedDefaultCandidate).ToList();
        var changes = selected.Select(difference => new ConfigMigrationChange(
            difference.Key, difference.CurrentValue, difference.DefaultValue)).ToList();
        if (previousVersion != DefaultConfigFile.TemplateVersion)
            changes.Add(new("template_version", previousVersion?.ToString(CultureInfo.InvariantCulture), DefaultConfigFile.TemplateVersion.ToString(CultureInfo.InvariantCulture)));

        if (!dryRun && changes.Count > 0)
        {
            foreach (var difference in selected)
                Set(root, difference.Key, difference.DefaultValue);
            root["template_version"] = DefaultConfigFile.TemplateVersion;
            Save(path, root);
        }

        var preserved = differences.Except(selected).ToList();
        return new(path, dryRun, previousVersion, DefaultConfigFile.TemplateVersion, changes, preserved);
    }

    private static IReadOnlyList<ConfigDefaultDifference> Differences(TomlTable root, int? recordedVersion)
    {
        var differences = new List<ConfigDefaultDifference>();
        if (Find(root, "providers.libex.region") is { } regionValue)
        {
            var region = Convert.ToString(regionValue, CultureInfo.InvariantCulture) ?? string.Empty;
            if (!region.Equals("de", StringComparison.OrdinalIgnoreCase))
            {
                var generated = recordedVersion is null or < 2
                    && region.Equals("us", StringComparison.OrdinalIgnoreCase)
                    && Convert.ToString(Find(root, "providers.libex.type"), CultureInfo.InvariantCulture)
                        ?.Equals("libex", StringComparison.OrdinalIgnoreCase) is true;
                differences.Add(new(
                    "providers.libex.region",
                    region,
                    "de",
                    generated,
                    generated
                        ? "value matches the Libex marketplace generated by template version 1"
                        : "value differs from the current default and is treated as an explicit customization"));
            }
        }
        return differences;
    }

    private (string Path, TomlTable Root) Load(string? explicitPath)
    {
        var path = paths.Resolve(explicitPath);
        if (!File.Exists(path) && paths.UsesPlatformDefault(explicitPath))
            DefaultConfigFile.Create(path);
        if (!File.Exists(path))
            throw new AudiobookMetaException(
                $"Configuration file was not found: {path}", ExitCodes.Configuration,
                "Select an existing file with BOOKMETA_CONFIG/--config.");
        try
        {
            var root = TomlSerializer.Deserialize<TomlTable>(File.ReadAllText(path), new TomlSerializerOptions { SourceName = path });
            return (path, root ?? throw ConfigError("configuration is empty"));
        }
        catch (TomlException exception)
        {
            throw new AudiobookMetaException(
                $"Configuration is invalid: {exception.Message}", ExitCodes.Configuration,
                "Correct the TOML syntax before inspecting or migrating defaults.", exception);
        }
    }

    private static void Save(string path, TomlTable root)
    {
        var content = TomlSerializer.Serialize(root, new TomlSerializerOptions { WriteIndented = true });
        DefaultConfigFile.WriteAtomically(path, content.EndsWith('\n') ? content : content + Environment.NewLine);
    }

    private static int? OptionalInteger(TomlTable root, string key)
        => root.TryGetValue(key, out var value) ? Convert.ToInt32(value, CultureInfo.InvariantCulture) : null;

    private static object? Find(TomlTable root, string key)
    {
        object? current = root;
        foreach (var part in key.Split('.'))
        {
            if (current is not TomlTable table || !table.TryGetValue(part, out current))
                return null;
        }
        return current;
    }

    private static void Set(TomlTable root, string key, object value)
    {
        var parts = key.Split('.');
        var table = root;
        foreach (var part in parts[..^1])
            table = table[part] as TomlTable ?? throw ConfigError($"missing table '{part}'");
        table[parts[^1]] = value;
    }

    private static AudiobookMetaException ConfigError(string message)
        => new($"Configuration migration failed: {message}.", ExitCodes.Configuration,
            "Run 'dotnet audiobookmeta config validate' and correct the file before retrying.");
}
